# These are supported funding model platforms

sukhdevsinghshekhawat: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
Kickstarter:

Indiegogo:

GoFundMe:

SeedInvest:

Crowdcube:

Republic:

Patreon:

Buy Me a Coffee:

Ko-fi:

Open Collective:

GitHub Sponsors:
